### ISSUE TITLE
don't work the scripts failed tests 

### ISSUE THREAD

**Issue by tridoxx** [GetDKAN/dkan-ddev-addon#12]
![image](https://user-images.githubusercontent.com/22879539/187998456-fabc868e-cea5-4a82-9506-bb3ca40621f8.png)
Hi, I'm trying to run and it throws me errors of tests not passed, I see that maybe there are packages that try to install, but they don't pass, maybe it's because they use a specific Linux distro, for that? 
![image](https://user-images.githubusercontent.com/22879539/187998796-f4e7a2fd-c1b0-4201-ae2e-e45e30b2c62b.png)

**Comment by tridoxx** [comment]
Hi dan thanks for you response, i only reboot intances of docker and reinstall and it work

**Comment by janette** [comment]
Thanks @tridoxx for testing it out. Keep us posted if you run into any other issues.
