### ISSUE TITLE
Separate sample content into its own command

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan-ddev-addon#7]
Add a dkan-sample-content command, move the sample content stuff in there, and replace them in demo with the new command.

**Comment by paul-m** [comment]
To test:
```
mkdir my-project && cd my_project
ddev config --auto
ddev get https://github.com/GetDKAN/dkan-ddev-addon/archive/refs/heads/7-separate-sample-content-into-its-own-command.tar.gz
ddev restart
ddev dkan-init
ddev dkan-site-install
ddev dkan-sample-content
```

At this point you can do `ddev launch` to see the front page of the site with some sample content on it.
